In [1]:
# !rm -rf data/synthetic_train
from synthetic_data import generate_synthetic
generate_synthetic("data/BIPED/BIPED/edges/imgs/train/rgbr/real", 1, 9)

Thinning not available (cv2.ximgproc issue).
Generating real image based samples...


100%|██████████| 2/2 [00:00<00:00, 15.91it/s]

Starting generation of 9 enhanced synthetic samples...
Using 31 worker process(es).
Starting parallel execution...



Generating Samples:   0%|          | 0/9 [00:00<?, ?it/s]

Could not place 1 objects within constraints after 200 attempts.


[ WARN:0@0.338] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/image_446.png'): can't open/read file: check file path/integrity


Could not place 2 objects within constraints after 200 attempts.


[ WARN:0@8.343] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/image_152.png'): can't open/read file: check file path/integrity
[ WARN:0@15.519] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/image_479.png'): can't open/read file: check file path/integrity
[ WARN:0@15.539] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/image_492.png'): can't open/read file: check file path/integrity
[ WARN:0@21.931] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/image_222.png'): can't open/read file: check file path/integrity
[ WARN:0@23.039] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/image_543.png'): can't open/read file: check file path/integrity
[ WARN:0@23.057] global loadsave.cpp:268 findDecoder imread_('data/textures/data/textures/lentils1-b.png'): can't open/read file: check file path/integrity
[ WARN:0@23.460] global loadsave.cpp:268 findDecoder imread_('data/tex


Generation complete.
Successfully generated 9/9 samples.
Total time: 52.17 seconds
Average time per image: 5.80 seconds


In [3]:
#data augmentation
from data_augmentation import run_augmentation
run_augmentation('data/synthetic_train', rotation = True)

=========== Data augmentation just for 720x1280 image size ==============
Image augmentation by splitting up have started!
Directories have been created:  data/synthetic_train/BIPED/edges/imgs/train/rgbr/aug
Directories have been created:  data/synthetic_train/BIPED/edges/edge_maps/train/rgbr/aug
Directories have been created:  data/synthetic_train/BIPED/edges/imgs/train/rgbr/aug/p1
Directories have been created:  data/synthetic_train/BIPED/edges/imgs/train/rgbr/aug/p2
Directories have been created:  data/synthetic_train/BIPED/edges/edge_maps/train/rgbr/aug/p1
Directories have been created:  data/synthetic_train/BIPED/edges/edge_maps/train/rgbr/aug/p2
saved image:  RGB_011.jpg RGB_011.png
saved image:  RGB_036.jpg RGB_036.png
saved image:  RGB_101.jpg RGB_101.png
saved image:  RGB_130.jpg RGB_130.png
saved image:  RGB_148.jpg RGB_148.png
saved image:  RGB_241.jpg RGB_241.png
...splitting up augmentation done!
data saved in:  ['p1', 'p2', 'real'] and in ['p1', 'p2', 'real']
Image augmen

In [ ]:
from teed import main
main()

In [ ]:
# from pathlib import Path
# import cv2

# def validate_images(texture_dir):
#     texture_dir = Path(texture_dir)
#     texture_files = list(texture_dir.glob('*'))
#     valid_images = []
#     invalid_images = []

#     for file in texture_files:
#         img = cv2.imread(str(file))
#         if img is None:
#             print(f"Invalid image: {file}")
#             invalid_images.append(file)
#         else:
#             valid_images.append(file)
    
#     return valid_images, invalid_images

# if __name__ == "__main__":
#     texture_directory = "data/textures"
#     valid, invalid = validate_images(texture_directory)
#     print(f"Valid images count: {len(valid)}")
#     print(f"Invalid images count: {len(invalid)}")

In [1]:

import subprocess
def call_ods_ois(model, mat_dir):
    # Path to the external Python interpreter if different from the main project's
    external_python = ".venv/bin/python3"
    
    # Build the command
    cmd = [
        external_python,
        "main.py",
        "--alg", "TEED " + model,
        "--model_name_list", model,
        "--result_dir", "../../" + mat_dir,
        "--save_dir", "../../" + mat_dir + "/eval_output",
        "--gt_dir", "../../data/UDED/gt_mat",
        "--key", "result",
        "--file_format", ".mat",
        "--workers", "-1"
    ]
    
    # Call the script, changing to its directory
    subprocess.run(cmd, cwd="external/edge_eval")

In [2]:
import matplotlib.pyplot as plt
plt.switch_backend('Agg')
for i in range(7):
    mat_dir = f"checkpoints/CLASSIC/{i}/UDED_res/result_mat"
    call_ods_ois("CLASSIC", mat_dir)

Traceback (most recent call last):
  File "/home/pramesh/teed/external/edge_eval/main.py", line 5, in <module>
    from eval_edge import eval_edge
  File "/home/pramesh/teed/external/edge_eval/eval_edge.py", line 5, in <module>
    from impl.edges_eval_plot import edges_eval_plot
  File "/home/pramesh/teed/external/edge_eval/impl/edges_eval_plot.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/home/pramesh/teed/external/edge_eval/.venv/lib/python3.9/site-packages/matplotlib/__init__.py", line 1273, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/home/pramesh/teed/external/edge_eval/.venv/lib/python3.9/site-packages/matplotlib/__init__.py", line 741, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt

In [1]:
from utils.run_eval_all import run_eval_all
run_eval_all()

Number of GPU's available: 1
Pytorch version: 2.6.0+cu124
Trainimage mean: [104.007, 116.669, 122.679, 137.86]
Test image mean: [104.007, 116.669, 122.679, 137.86]
output_dir: result/checkpoints_35_165_rotation_true/CLASSIC/0/0_model.pth
Restoring weights from: checkpoints_35_165_rotation_true/CLASSIC/0/0_model.pth
['01-0843x4.png']: torch.Size([1, 3, 512, 768])
['02-0868x4.png']: torch.Size([1, 3, 512, 768])
['03-35028.png']: torch.Size([1, 3, 488, 728])
['04-0896x4.png']: torch.Size([1, 3, 512, 768])
['05-WIREFRAME-2.png']: torch.Size([1, 3, 504, 752])
['06-elephant_3.png']: torch.Size([1, 3, 512, 512])
['07-CITYSCAPES-2C.png']: torch.Size([1, 3, 720, 720])
['08-ADE20K-1C.png']: torch.Size([1, 3, 720, 720])
['09-MDBD-1C.png']: torch.Size([1, 3, 720, 720])
['10-196062.png']: torch.Size([1, 3, 488, 728])
['11-NYUD-2.png']: torch.Size([1, 3, 640, 848])
['12-cameraman.png']: torch.Size([1, 3, 536, 536])
['13-BIPED-1C.png']: torch.Size([1, 3, 720, 720])
['14-comic.png']: torch.Size([1, 3,

In [1]:
from inference import run_inference
run_inference()

Number of GPU's available: 1
Pytorch version: 2.6.0+cu124
Trainimage mean: [104.007, 116.669, 122.679, 137.86]
Test image mean: [104.007, 116.669, 122.679, 137.86]
output_dir: result/checkpoints/CLASSIC/5/5_model.pth
Restoring weights from: checkpoints/CLASSIC/5/5_model.pth
['01-0843x4.png']: torch.Size([1, 3, 512, 768])
['02-0868x4.png']: torch.Size([1, 3, 512, 768])
['03-35028.png']: torch.Size([1, 3, 488, 728])
['04-0896x4.png']: torch.Size([1, 3, 512, 768])
['05-WIREFRAME-2.png']: torch.Size([1, 3, 504, 752])
['06-elephant_3.png']: torch.Size([1, 3, 512, 512])
['07-CITYSCAPES-2C.png']: torch.Size([1, 3, 720, 720])
['08-ADE20K-1C.png']: torch.Size([1, 3, 720, 720])
['09-MDBD-1C.png']: torch.Size([1, 3, 720, 720])
['10-196062.png']: torch.Size([1, 3, 488, 728])
['11-NYUD-2.png']: torch.Size([1, 3, 640, 848])
['12-cameraman.png']: torch.Size([1, 3, 536, 536])
['13-BIPED-1C.png']: torch.Size([1, 3, 720, 720])
['14-comic.png']: torch.Size([1, 3, 544, 376])
['15-P1020854.png']: torch.Siz

In [13]:
import cv2
import os
import numpy as np
def get_mean(folder_path):
    mean_bgr = np.zeros(3)  # B, G, R
    count = 0
    folder_path = os.path.join(folder_path, 'edges/imgs/train/rgbr/real')
    for file in os.listdir(folder_path):
        if file.endswith('.jpg'):
            img = cv2.imread(os.path.join(folder_path, file))
            mean_bgr += np.mean(img, axis=(0, 1))
            count += 1
    if count == 0:
        raise ValueError("No images found in folder.")  
    print(count)
    return mean_bgr / count

In [14]:
get_mean('data/BIPED/BIPED/')

200


array([160.91306472, 160.27534432, 162.23877227])

In [12]:
get_mean('data/BIPED/BIPED/')

array([160.91306472, 160.27534432, 162.23877227])

In [17]:
def get_mean(folder_path):
    sum_bgr = np.zeros(3)  # B, G, R
    total_pixels = 0
    folder_path = os.path.join(folder_path, 'edges/imgs/train/rgbr/real')
    
    for file in os.listdir(folder_path):
        if file.endswith('.jpg') or file.endswith('.png'):
            img = cv2.imread(os.path.join(folder_path, file))
            h, w, c = img.shape
            sum_bgr += np.sum(img, axis=(0, 1))
            total_pixels += h * w

    if total_pixels == 0:
        raise ValueError("No images found in folder.")
    
    mean_bgr = sum_bgr / total_pixels
    print("Total images:", len(os.listdir(folder_path)))
    print("Total pixels:", total_pixels)
    return mean_bgr

In [18]:
get_mean('data/BIPED/BIPED/')

Total images: 200
Total pixels: 184320000


array([7.48558089, 7.48558089, 7.48558089])